// Defense vs 3Bet IP / OOP (Green Charts, стр. 10 и 11).
//
// Три цвета в PDF: зелёный (колл 3бета), красный (4бет и фолд на 5бет),
// фиолетовый (4бет и колл 5бет пуша). В отличие от threeBetIP.ts, здесь
// красный/фиолетовый держатся как ДВА РАЗНЫХ действия одного kind="raise" —
// для равновесия диапазона (фильтры всё/4бет/колл) это без разницы, обе
// считаются 4бетом, но раздельные action.color позволяют красить матрицу
// теми же цветами, что и оригинальный чарт (режим «цвета пресета»).
//
// Составные ячейки здесь не всегда 50/50 — встречаются и четверти (25/75).
// Доля пикселей округляется до ближайшей четверти: always=1.0,
// threeQuarter=0.75, situational=0.5, quarter=0.25.
//
// Сгенерировано tools/gen_def_vs_3bet.py — не редактировать руками.

import { RangePreset } from "./types";

export const DEF3BETIP_PRESETS: RangePreset[] = [
  {
    id: "def3bet-ip-6",
    group: "DEF3BETIP",
    position: "IP vs 3bet 6%",
    title: "Def vs 3Bet IP · 6%",
    subtitle: "Диапазон защиты в позиции, блайнд 3бетит 6%",
    actions: [
      {
        kind: "call",
        label: "колл",
        color: "green",
        always: ["AKs", "AQs", "AKo", "QQ", "JJ", "TT"],
        threeQuarter: ["AJs", "KQs", "KJs"],
        situational: [],
        quarter: [],
      },
      {
        kind: "raise",
        label: "4бет-фолд",
        color: "red",
        always: [],
        threeQuarter: [],
        situational: [],
        quarter: ["AJs", "KQs", "KJs"],
      },
      {
        kind: "raise",
        label: "4бет-пуш",
        color: "purple",
        always: ["AA", "KK"],
        threeQuarter: [],
        situational: [],
        quarter: [],
      },
    ],
  },
  {
    id: "def3bet-ip-8",
    group: "DEF3BETIP",
    position: "IP vs 3bet 8%",
    title: "Def vs 3Bet IP · 8%",
    subtitle: "Диапазон защиты в позиции, блайнд 3бетит 8%",
    actions: [
      {
        kind: "call",
        label: "колл",
        color: "green",
        always: ["AQs", "AKo", "QQ", "QJs", "JJ", "TT", "99"],
        threeQuarter: ["AKs", "AJs", "ATs", "KQs", "KJs", "KTs"],
        situational: [],
        quarter: [],
      },
      {
        kind: "raise",
        label: "4бет-фолд",
        color: "red",
        always: [],
        threeQuarter: [],
        situational: [],
        quarter: ["AJs", "ATs", "KQs", "KJs", "KTs"],
      },
      {
        kind: "raise",
        label: "4бет-пуш",
        color: "purple",
        always: ["AA", "KK"],
        threeQuarter: [],
        situational: [],
        quarter: ["AKs"],
      },
    ],
  },
  {
    id: "def3bet-ip-12",
    group: "DEF3BETIP",
    position: "IP vs 3bet 12%",
    title: "Def vs 3Bet IP · 12%",
    subtitle: "Диапазон защиты в позиции, блайнд 3бетит 12%",
    actions: [
      {
        kind: "call",
        label: "колл",
        color: "green",
        always: ["AQs", "AJs", "ATs", "A9s", "A8s", "A7s", "KQs", "KJs", "KTs", "K9s", "AQo", "KQo", "QJs", "QTs", "Q9s", "AJo", "JTs", "J9s", "TT", "T9s", "99", "88", "77", "66"],
        threeQuarter: [],
        situational: ["A5s", "A4s", "A3s", "AKo", "JJ"],
        quarter: ["98s", "87s", "76s", "65s"],
      },
      {
        kind: "raise",
        label: "4бет-фолд",
        color: "red",
        always: [],
        threeQuarter: [],
        situational: ["A5s", "A4s", "A3s"],
        quarter: ["A6s", "A2s", "K8s", "K7s", "K6s", "K5s", "K4s", "K3s", "K2s", "Q8s", "Q7s", "ATo"],
      },
      {
        kind: "raise",
        label: "4бет-пуш",
        color: "purple",
        always: ["AA", "AKs", "KK", "QQ"],
        threeQuarter: [],
        situational: ["AKo", "JJ"],
        quarter: [],
      },
    ],
  },
  {
    id: "def3bet-ip-10",
    group: "DEF3BETIP",
    position: "IP vs 3bet 10%",
    title: "Def vs 3Bet IP · 10%",
    subtitle: "Диапазон защиты в позиции, блайнд 3бетит 10%",
    actions: [
      {
        kind: "call",
        label: "колл",
        color: "green",
        always: ["AQs", "AJs", "ATs", "KQs", "KJs", "KTs", "AQo", "QJs", "QTs", "JJ", "JTs", "TT", "99", "88", "77"],
        threeQuarter: ["AKo"],
        situational: ["QQ"],
        quarter: [],
      },
      {
        kind: "raise",
        label: "4бет-фолд",
        color: "red",
        always: ["A5s", "A4s", "A3s"],
        threeQuarter: [],
        situational: [],
        quarter: ["KQo", "AJo"],
      },
      {
        kind: "raise",
        label: "4бет-пуш",
        color: "purple",
        always: ["AA", "AKs", "KK"],
        threeQuarter: [],
        situational: ["QQ"],
        quarter: ["AKo"],
      },
    ],
  },
  {
    id: "def3bet-ip-14",
    group: "DEF3BETIP",
    position: "IP vs 3bet 14%",
    title: "Def vs 3Bet IP · 14%",
    subtitle: "Диапазон защиты в позиции, блайнд 3бетит 14%",
    actions: [
      {
        kind: "call",
        label: "колл",
        color: "green",
        always: ["AJs", "ATs", "A9s", "KQs", "KJs", "KTs", "K9s", "AQo", "KQo", "QJs", "QTs", "Q9s", "AJo", "JTs", "J9s", "T9s", "99", "88", "77", "66"],
        threeQuarter: ["AQs", "A8s", "A7s"],
        situational: ["A5s", "A4s", "A3s", "TT", "98s", "87s", "76s", "65s", "55"],
        quarter: ["J8s", "T8s"],
      },
      {
        kind: "raise",
        label: "4бет-фолд",
        color: "red",
        always: [],
        threeQuarter: [],
        situational: ["A6s", "A5s", "A4s", "A3s", "A2s", "K8s", "K7s", "K6s", "K5s", "K4s", "K3s", "K2s", "Q8s", "Q7s", "KJo", "ATo"],
        quarter: ["A8s", "A7s"],
      },
      {
        kind: "raise",
        label: "4бет-пуш",
        color: "purple",
        always: ["AA", "AKs", "AKo", "KK", "QQ", "JJ"],
        threeQuarter: [],
        situational: ["TT"],
        quarter: ["AQs"],
      },
    ],
  },
];

export const DEF3BETOOP_PRESETS: RangePreset[] = [
  {
    id: "def3bet-oop-8",
    group: "DEF3BETOOP",
    position: "OOP vs 3bet 8%",
    title: "Def vs 3Bet OOP · 8%",
    subtitle: "Диапазон защиты вне позиции от 3бета в 8%",
    actions: [
      {
        kind: "call",
        label: "колл",
        color: "green",
        always: [],
        threeQuarter: ["AQs"],
        situational: ["TT"],
        quarter: ["AJs", "AKo", "KQs", "JJ"],
      },
      {
        kind: "raise",
        label: "4бет-фолд",
        color: "red",
        always: [],
        threeQuarter: ["AJs", "AKo", "KQs", "KJs", "JJ"],
        situational: ["AQo", "TT"],
        quarter: ["AQs", "ATs", "99"],
      },
      {
        kind: "raise",
        label: "4бет-пуш",
        color: "purple",
        always: ["AA", "AKs", "KK", "QQ"],
        threeQuarter: [],
        situational: [],
        quarter: [],
      },
    ],
  },
  {
    id: "def3bet-oop-10",
    group: "DEF3BETOOP",
    position: "OOP vs 3bet 10%",
    title: "Def vs 3Bet OOP · 10%",
    subtitle: "Диапазон защиты вне позиции от 3бета в 10%",
    actions: [
      {
        kind: "call",
        label: "колл",
        color: "green",
        always: [],
        threeQuarter: ["AQs"],
        situational: ["AJs", "TT"],
        quarter: ["KQs", "KJs", "JJ"],
      },
      {
        kind: "raise",
        label: "4бет-фолд",
        color: "red",
        always: [],
        threeQuarter: ["KQs", "KJs", "AQo", "JJ"],
        situational: ["AJs", "ATs", "KTs", "TT"],
        quarter: ["AQs", "99"],
      },
      {
        kind: "raise",
        label: "4бет-пуш",
        color: "purple",
        always: ["AA", "AKs", "AKo", "KK", "QQ"],
        threeQuarter: [],
        situational: [],
        quarter: [],
      },
    ],
  },
  {
    id: "def3bet-oop-18",
    group: "DEF3BETOOP",
    position: "OOP vs 3bet 18% (SB vs BB)",
    title: "Def vs 3Bet OOP · 18%",
    subtitle: "Диапазон защиты вне позиции от 3бета в 18%, SB vs BB",
    actions: [
      {
        kind: "call",
        label: "колл",
        color: "green",
        always: ["AJs", "ATs", "A9s", "A8s", "A7s", "A6s", "A5s", "A4s", "A3s", "KQs", "KJs", "KTs", "K9s", "QJs", "QTs", "Q9s", "JTs", "J9s", "T9s", "99", "88", "77", "66", "55"],
        threeQuarter: [],
        situational: ["AQs", "AQo", "KQo", "TT"],
        quarter: ["AJo"],
      },
      {
        kind: "raise",
        label: "4бет-фолд",
        color: "red",
        always: ["A2s"],
        threeQuarter: ["AJo"],
        situational: ["AQo", "KQo", "KJo", "ATo"],
        quarter: [],
      },
      {
        kind: "raise",
        label: "4бет-пуш",
        color: "purple",
        always: ["AA", "AKs", "AKo", "KK", "QQ", "JJ"],
        threeQuarter: [],
        situational: ["AQs", "TT"],
        quarter: [],
      },
    ],
  },
  {
    id: "def3bet-oop-12",
    group: "DEF3BETOOP",
    position: "OOP vs 3bet 12%",
    title: "Def vs 3Bet OOP · 12%",
    subtitle: "Диапазон защиты вне позиции от 3бета в 12%",
    actions: [
      {
        kind: "call",
        label: "колл",
        color: "green",
        always: ["AQs", "AJs", "KQs", "77"],
        threeQuarter: ["QJs", "QTs", "JTs", "88"],
        situational: ["ATs", "TT", "99"],
        quarter: ["KJs", "KTs"],
      },
      {
        kind: "raise",
        label: "4бет-фолд",
        color: "red",
        always: ["AQo"],
        threeQuarter: ["KJs", "KTs"],
        situational: ["ATs", "TT", "99"],
        quarter: ["QJs", "QTs", "JTs", "88"],
      },
      {
        kind: "raise",
        label: "4бет-пуш",
        color: "purple",
        always: ["AA", "AKs", "AKo", "KK", "QQ", "JJ"],
        threeQuarter: [],
        situational: [],
        quarter: [],
      },
    ],
  },
];
